# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('monday_start', models.DateTimeField()),
                ('monday_end', models.DateTimeField()),
                ('monday_cabinet', models.CharField(max_length=20)),
                ('tuesday_start', models.DateTimeField()),
                ('tuesday_end', models.DateTimeField()),
                ('tuesday_cabinet', models.CharField(max_length=20)),
                ('wednesday_start', models.DateTimeField()),
                ('wednesday_end', models.DateTimeField()),
                ('wednesday_cabinet', models.CharField(max_length=20)),
                ('thursday_start', models.DateTimeField()),
                ('thursday_end', models.DateTimeField()),
                ('thursday_cabinet', models.CharField(max_length=20)),
                ('friday_start', models.DateTimeField()),
                ('friday_end', models.DateTimeField()),
                ('friday_cabinet', models.CharField(max_length=20)),
                ('saturday_start', models.DateTimeField()),
                ('saturday_end', models.DateTimeField()),
                ('saturday_cabinet', models.CharField(max_length=20)),
                ('sunday_start', models.DateTimeField()),
                ('sunday_end', models.DateTimeField()),
                ('sunday_cabinet', models.CharField(max_length=20)),
                ('duration', models.DurationField()),
                ('specialization', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-add_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('date_of_receipt', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edoctor.Doctor')),
            ],
            options={
                'ordering': ['-add_date'],
                'abstract': False,
            },
        ),
    ]
