# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edoctor', '0003_auto_20170325_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='talon',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talon',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
